# Generated by Django 5.0.6 on 2024-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('is_active', models.BooleanField(verbose_name=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
