# Generated by Django 5.0.6 on 2024-05-30 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto_app', '0004_contact_category_contact_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacto_app.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacto_app.customuser'),
        ),
    ]
